GRANT USAGE ON SCHEMA public TO tablenow_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO tablenow_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO tablenow_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO tablenow_app;

ALTER DEFAULT PRIVILEGES FOR ROLE tablenow_admin IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO tablenow_app;
ALTER DEFAULT PRIVILEGES FOR ROLE tablenow_admin IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO tablenow_app;
ALTER DEFAULT PRIVILEGES FOR ROLE tablenow_admin IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO tablenow_app;
