services:
  proxy:
    depends_on:
      core-api: { condition: service_healthy }
    environment:
      API_DOMAIN: ${API_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../cloud/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

  mailpit:
    profiles: ["debug-mail"]

volumes:
  caddy-data:
  caddy-config:
