import type { ComputerUseOverview, Session, Workspace } from "./types";

const fixtureNow = Date.now();
const minute = 60_000;
const hour = 60 * minute;
const day = 24 * hour;

function relativeIso(offsetMilliseconds: number): string {
  return new Date(fixtureNow + offsetMilliseconds).toISOString();
}

function metricDate(daysAgo: number): string {
  return new Date(fixtureNow - daysAgo * day).toISOString().slice(0, 10);
}

export const publicPilotSession: Session = {
  user: {
    id: "public-pilot-viewer",
    email: "visiteur@pilot.tablenow.test",
    displayName: "Visiteur pilote",
  },
  tenant: {
    id: "public-pilot-tenant",
    name: "TableNow — Groupe fictif",
    slug: "public-pilot",
    onboardingComplete: true,
  },
  membership: { role: "viewer" },
  csrfToken: null,
};

const metrics: Workspace["metrics"] = Array.from({ length: 14 }, (_, index) => {
  const daysAgo = 13 - index;
  const weekdayShape = [0, 110, 180, 260, 430, 650, 510][index % 7] ?? 0;

  return [
    {
      restaurantId: "public-pilot-paris",
      date: metricDate(daysAgo),
      revenueCaptured: 980 + weekdayShape + index * 19,
      covers: 48 + (index % 5) * 6,
      callsHandled: 14 + (index % 6) * 2,
      conversionRate: 66 + (index % 5) * 2.1,
      timeSavedMinutes: 76 + index * 3,
    },
    {
      restaurantId: "public-pilot-lyon",
      date: metricDate(daysAgo),
      revenueCaptured: 710 + Math.round(weekdayShape * 0.72) + index * 14,
      covers: 35 + (index % 4) * 5,
      callsHandled: 10 + (index % 5) * 2,
      conversionRate: 61 + (index % 4) * 2.4,
      timeSavedMinutes: 54 + index * 2,
    },
  ];
}).flat();

export const publicPilotWorkspace: Workspace = {
  summary: {
    occupancyPercent: 71,
    openDecisions: 3,
    availableTables: 12,
    inventoryAlerts: 2,
    revenueCapturedToday: 690,
    timeSavedMinutes: 248,
    coversToday: 128,
  },
  restaurantSummaries: [
    {
      restaurantId: "public-pilot-paris",
      occupancyPercent: 76,
      openDecisions: 2,
      availableTables: 5,
      inventoryAlerts: 1,
      revenueCapturedToday: 410,
      timeSavedMinutes: 146,
      coversToday: 78,
    },
    {
      restaurantId: "public-pilot-lyon",
      occupancyPercent: 64,
      openDecisions: 1,
      availableTables: 7,
      inventoryAlerts: 1,
      revenueCapturedToday: 280,
      timeSavedMinutes: 102,
      coversToday: 50,
    },
  ],
  restaurants: [
    {
      id: "public-pilot-paris",
      name: "Maison Sillage — Démonstration",
      slug: "maison-sillage-demo",
      address: "12 rue Exemple, 75000 Paris — adresse fictive",
      phone: "+33 1 00 00 00 00",
      timezone: "Europe/Paris",
      capacity: 84,
      isDemo: true,
    },
    {
      id: "public-pilot-lyon",
      name: "Atelier Rivage — Démonstration",
      slug: "atelier-rivage-demo",
      address: "8 quai Démonstration, 69000 Lyon — adresse fictive",
      phone: "+33 4 00 00 00 00",
      timezone: "Europe/Paris",
      capacity: 58,
      isDemo: true,
    },
  ],
  reservations: [
    {
      id: "public-reservation-1",
      restaurantId: "public-pilot-paris",
      guestName: "Camille Laurent",
      guestEmail: "camille.laurent@example.test",
      guestPhone: "+33 6 00 00 00 01",
      startsAt: relativeIso(75 * minute),
      partySize: 2,
      status: "confirmed",
      source: "phone",
      notes: "Anniversaire — prévoir une table calme.",
    },
    {
      id: "public-reservation-2",
      restaurantId: "public-pilot-paris",
      guestName: "Groupe Atlas",
      guestEmail: "atlas@example.test",
      guestPhone: "+33 6 00 00 00 02",
      startsAt: relativeIso(120 * minute),
      partySize: 10,
      status: "pending",
      source: "web",
      notes: "Menu groupe et acompte à confirmer.",
    },
    {
      id: "public-reservation-3",
      restaurantId: "public-pilot-paris",
      guestName: "Nora Benali",
      guestEmail: "nora.benali@example.test",
      guestPhone: "+33 6 00 00 00 03",
      startsAt: relativeIso(165 * minute),
      partySize: 4,
      status: "confirmed",
      source: "manual",
      notes: "Allergie aux fruits à coque signalée.",
    },
    {
      id: "public-reservation-4",
      restaurantId: "public-pilot-paris",
      guestName: "Hugo Martin",
      guestEmail: null,
      guestPhone: "+33 6 00 00 00 04",
      startsAt: relativeIso(-25 * minute),
      partySize: 3,
      status: "seated",
      source: "copilot",
      notes: null,
    },
    {
      id: "public-reservation-5",
      restaurantId: "public-pilot-lyon",
      guestName: "Salma Robert",
      guestEmail: "salma.robert@example.test",
      guestPhone: "+33 6 00 00 00 05",
      startsAt: relativeIso(90 * minute),
      partySize: 5,
      status: "confirmed",
      source: "phone",
      notes: "Chaise haute demandée.",
    },
    {
      id: "public-reservation-6",
      restaurantId: "public-pilot-lyon",
      guestName: "Émilie Perrin",
      guestEmail: "emilie.perrin@example.test",
      guestPhone: null,
      startsAt: relativeIso(210 * minute),
      partySize: 2,
      status: "pending",
      source: "web",
      notes: null,
    },
    {
      id: "public-reservation-7",
      restaurantId: "public-pilot-lyon",
      guestName: "Mathis Bernard",
      guestEmail: null,
      guestPhone: "+33 6 00 00 00 07",
      startsAt: relativeIso(-3 * hour),
      partySize: 4,
      status: "completed",
      source: "manual",
      notes: null,
    },
    {
      id: "public-reservation-8",
      restaurantId: "public-pilot-paris",
      guestName: "Lina Morel",
      guestEmail: "lina.morel@example.test",
      guestPhone: null,
      startsAt: relativeIso(4 * hour),
      partySize: 2,
      status: "cancelled",
      source: "web",
      notes: "Annulation client enregistrée.",
    },
  ],
  communications: [
    {
      id: "public-communication-1",
      restaurantId: "public-pilot-paris",
      channel: "phone",
      direction: "inbound",
      contactName: "Camille Laurent",
      subject: "Réservation confirmée",
      summary: "TableNow a compris la demande, vérifié le créneau et confirmé deux couverts.",
      status: "handled",
      occurredAt: relativeIso(-12 * minute),
    },
    {
      id: "public-communication-2",
      restaurantId: "public-pilot-paris",
      channel: "email",
      direction: "inbound",
      contactName: "Groupe Atlas",
      subject: "Demande de groupe",
      summary: "Dix couverts souhaitent un menu unique ; la décision commerciale a été transmise à la direction.",
      status: "escalated",
      occurredAt: relativeIso(-28 * minute),
    },
    {
      id: "public-communication-3",
      restaurantId: "public-pilot-lyon",
      channel: "whatsapp",
      direction: "inbound",
      contactName: "Salma Robert",
      subject: "Chaise haute",
      summary: "La préférence a été ajoutée à la réservation et rendue visible à l’équipe de salle.",
      status: "handled",
      occurredAt: relativeIso(-39 * minute),
    },
    {
      id: "public-communication-4",
      restaurantId: "public-pilot-paris",
      channel: "instagram",
      direction: "inbound",
      contactName: "Client fictif",
      subject: "Question allergènes",
      summary: "La composition du dessert doit être confirmée par la cuisine avant de répondre.",
      status: "open",
      occurredAt: relativeIso(-51 * minute),
    },
    {
      id: "public-communication-5",
      restaurantId: "public-pilot-lyon",
      channel: "phone",
      direction: "inbound",
      contactName: "Émilie Perrin",
      subject: "Réservation à confirmer",
      summary: "Le créneau souhaité est disponible ; il manque uniquement une coordonnée de rappel.",
      status: "open",
      occurredAt: relativeIso(-68 * minute),
    },
    {
      id: "public-communication-6",
      restaurantId: "public-pilot-paris",
      channel: "sms",
      direction: "outbound",
      contactName: "Nora Benali",
      subject: "Rappel de réservation",
      summary: "Le rappel et la note allergène ont été envoyés automatiquement.",
      status: "handled",
      occurredAt: relativeIso(-94 * minute),
    },
    {
      id: "public-communication-7",
      restaurantId: "public-pilot-lyon",
      channel: "email",
      direction: "inbound",
      contactName: "Agence Horizon fictive",
      subject: "Privatisation partielle",
      summary: "Une demande de vingt-deux couverts nécessite une proposition commerciale structurée.",
      status: "escalated",
      occurredAt: relativeIso(-2 * hour),
    },
  ],
  decisions: [
    {
      id: "public-decision-1",
      restaurantId: "public-pilot-paris",
      kind: "group_request",
      title: "Valider la demande du groupe Atlas",
      description: "Dix couverts à forte valeur demandent un menu unique et un devis avant confirmation.",
      priority: "high",
      status: "open",
      suggestedAction: "Accepter le créneau sous réserve d’un acompte fictif de 30 %.",
      dueAt: relativeIso(42 * minute),
      resolutionNote: null,
      createdAt: relativeIso(-35 * minute),
    },
    {
      id: "public-decision-2",
      restaurantId: "public-pilot-paris",
      kind: "allergen",
      title: "Faire confirmer la fiche allergène",
      description: "Une demande concerne un dessert susceptible de contenir des fruits à coque.",
      priority: "critical",
      status: "open",
      suggestedAction: "Demander une validation explicite à la cuisine avant toute réponse au client.",
      dueAt: relativeIso(18 * minute),
      resolutionNote: null,
      createdAt: relativeIso(-54 * minute),
    },
    {
      id: "public-decision-3",
      restaurantId: "public-pilot-lyon",
      kind: "private_event",
      title: "Répondre à la privatisation Horizon",
      description: "Vingt-deux couverts sont possibles, mais le renfort de salle n’est pas encore confirmé.",
      priority: "medium",
      status: "open",
      suggestedAction: "Poser une option de deux heures et vérifier le planning avant devis.",
      dueAt: relativeIso(95 * minute),
      resolutionNote: null,
      createdAt: relativeIso(-2 * hour),
    },
    {
      id: "public-decision-4",
      restaurantId: "public-pilot-lyon",
      kind: "capacity",
      title: "Ouvrir le dernier créneau de 21 h 30",
      description: "La capacité et l’équipe permettent d’ouvrir deux tables supplémentaires.",
      priority: "low",
      status: "approved",
      suggestedAction: "Publier deux tables de deux couverts.",
      dueAt: null,
      resolutionNote: "Validation fictive enregistrée par la direction.",
      createdAt: relativeIso(-5 * hour),
    },
  ],
  tasks: [
    {
      id: "public-task-1",
      restaurantId: "public-pilot-paris",
      title: "Brief équipe — allergies et demandes spéciales",
      category: "service",
      status: "open",
      assigneeName: "Responsable de salle",
      dueAt: relativeIso(35 * minute),
    },
    {
      id: "public-task-2",
      restaurantId: "public-pilot-paris",
      title: "Contrôler la mise en place de la terrasse",
      category: "opening",
      status: "in_progress",
      assigneeName: "Équipe du soir",
      dueAt: relativeIso(20 * minute),
    },
    {
      id: "public-task-3",
      restaurantId: "public-pilot-lyon",
      title: "Confirmer le renfort pour le groupe",
      category: "team",
      status: "open",
      assigneeName: "Direction Lyon",
      dueAt: relativeIso(70 * minute),
    },
    {
      id: "public-task-4",
      restaurantId: "public-pilot-lyon",
      title: "Réceptionner la livraison de boissons",
      category: "supplier",
      status: "done",
      assigneeName: "Maya",
      dueAt: relativeIso(-90 * minute),
    },
    {
      id: "public-task-5",
      restaurantId: "public-pilot-paris",
      title: "Vérifier le terminal de paiement mobile",
      category: "maintenance",
      status: "done",
      assigneeName: "Noah",
      dueAt: relativeIso(-2 * hour),
    },
  ],
  shifts: [
    {
      id: "public-shift-1",
      restaurantId: "public-pilot-paris",
      teamMemberName: "Maya Durand",
      roleTitle: "Responsable de salle",
      startsAt: relativeIso(-hour),
      endsAt: relativeIso(7 * hour),
      status: "confirmed",
    },
    {
      id: "public-shift-2",
      restaurantId: "public-pilot-paris",
      teamMemberName: "Léo Garnier",
      roleTitle: "Chef de rang",
      startsAt: relativeIso(-30 * minute),
      endsAt: relativeIso(6.5 * hour),
      status: "confirmed",
    },
    {
      id: "public-shift-3",
      restaurantId: "public-pilot-paris",
      teamMemberName: "Inès Petit",
      roleTitle: "Serveuse",
      startsAt: relativeIso(30 * minute),
      endsAt: relativeIso(6 * hour),
      status: "planned",
    },
    {
      id: "public-shift-4",
      restaurantId: "public-pilot-lyon",
      teamMemberName: "Noah Leroy",
      roleTitle: "Cuisine",
      startsAt: relativeIso(-2 * hour),
      endsAt: relativeIso(6 * hour),
      status: "confirmed",
    },
    {
      id: "public-shift-5",
      restaurantId: "public-pilot-lyon",
      teamMemberName: "Sarah Colin",
      roleTitle: "Cheffe de rang",
      startsAt: relativeIso(-hour),
      endsAt: relativeIso(6 * hour),
      status: "confirmed",
    },
    {
      id: "public-shift-6",
      restaurantId: "public-pilot-lyon",
      teamMemberName: "Amine Roy",
      roleTitle: "Runner",
      startsAt: relativeIso(45 * minute),
      endsAt: relativeIso(5.5 * hour),
      status: "planned",
    },
  ],
  inventory: [
    {
      id: "public-inventory-1",
      restaurantId: "public-pilot-paris",
      name: "Saumon frais",
      unit: "kg",
      quantity: 3.2,
      reorderThreshold: 4,
      status: "alert",
      updatedAt: relativeIso(-22 * minute),
    },
    {
      id: "public-inventory-2",
      restaurantId: "public-pilot-paris",
      name: "Crémant sans alcool",
      unit: "bouteilles",
      quantity: 18,
      reorderThreshold: 8,
      status: "healthy",
      updatedAt: relativeIso(-31 * minute),
    },
    {
      id: "public-inventory-3",
      restaurantId: "public-pilot-paris",
      name: "Pain au levain",
      unit: "unités",
      quantity: 42,
      reorderThreshold: 20,
      status: "healthy",
      updatedAt: relativeIso(-44 * minute),
    },
    {
      id: "public-inventory-4",
      restaurantId: "public-pilot-lyon",
      name: "Purée de framboise",
      unit: "kg",
      quantity: 1.4,
      reorderThreshold: 2,
      status: "alert",
      updatedAt: relativeIso(-17 * minute),
    },
    {
      id: "public-inventory-5",
      restaurantId: "public-pilot-lyon",
      name: "Eau pétillante",
      unit: "bouteilles",
      quantity: 36,
      reorderThreshold: 14,
      status: "healthy",
      updatedAt: relativeIso(-26 * minute),
    },
    {
      id: "public-inventory-6",
      restaurantId: "public-pilot-lyon",
      name: "Citron jaune",
      unit: "unités",
      quantity: 29,
      reorderThreshold: 12,
      status: "healthy",
      updatedAt: relativeIso(-36 * minute),
    },
  ],
  metrics,
  actions: [
    {
      id: "public-action-1",
      restaurantId: "public-pilot-paris",
      conversationId: "public-conversation-1",
      tool: "reservation.capacity",
      title: "Préparer deux tables supplémentaires",
      rationale: "La capacité, le rythme des arrivées et l’équipe fictive le permettent.",
      risk: "medium",
      approvalRequired: true,
      status: "proposed",
      createdAt: relativeIso(-16 * minute),
    },
    {
      id: "public-action-2",
      restaurantId: "public-pilot-lyon",
      conversationId: "public-conversation-2",
      tool: "inventory.review",
      title: "Préparer une demande fournisseur",
      rationale: "Le niveau fictif de purée de framboise est inférieur au seuil déclaré.",
      risk: "low",
      approvalRequired: true,
      status: "approved",
      createdAt: relativeIso(-75 * minute),
    },
    {
      id: "public-action-3",
      restaurantId: null,
      conversationId: "public-conversation-3",
      tool: "group.compare",
      title: "Comparer la charge des deux établissements",
      rationale: "La direction fictive souhaite répartir un renfort entre Paris et Lyon.",
      risk: "low",
      approvalRequired: false,
      status: "completed",
      createdAt: relativeIso(-3 * hour),
    },
  ],
};

export const publicPilotSystems: ComputerUseOverview = {
  systems: [
    {
      id: "public-system-paris-native",
      restaurantId: "public-pilot-paris",
      category: "reservations",
      provider: "tablenow",
      displayName: "Réservations TableNow — démonstration",
      accessMethod: "native",
      status: "ready",
      capabilities: ["reservation.read", "reservation.create", "reservation.update", "reservation.cancel"],
      isSourceOfTruth: true,
      priority: 10,
      updatedAt: relativeIso(-8 * minute),
    },
    {
      id: "public-system-paris-calendar",
      restaurantId: "public-pilot-paris",
      category: "reservations",
      provider: "google_calendar",
      displayName: "Calendrier de service fictif",
      accessMethod: "calendar",
      status: "ready",
      capabilities: ["reservation.read", "reservation.create"],
      isSourceOfTruth: false,
      priority: 30,
      updatedAt: relativeIso(-14 * minute),
    },
    {
      id: "public-system-paris-manual",
      restaurantId: "public-pilot-paris",
      category: "manual",
      provider: "paper",
      displayName: "Cahier de secours fictif",
      accessMethod: "manual",
      status: "ready",
      capabilities: ["reservation.read", "reservation.create", "reservation.update", "reservation.cancel"],
      isSourceOfTruth: false,
      priority: 90,
      updatedAt: relativeIso(-2 * hour),
    },
    {
      id: "public-system-lyon-browser",
      restaurantId: "public-pilot-lyon",
      category: "reservations",
      provider: "generic",
      displayName: "Logiciel métier fictif",
      accessMethod: "browser",
      status: "limited",
      capabilities: ["reservation.read", "reservation.create", "reservation.cancel"],
      isSourceOfTruth: true,
      priority: 20,
      updatedAt: relativeIso(-19 * minute),
    },
    {
      id: "public-system-lyon-native",
      restaurantId: "public-pilot-lyon",
      category: "reservations",
      provider: "tablenow",
      displayName: "TableNow de secours — démonstration",
      accessMethod: "native",
      status: "ready",
      capabilities: ["reservation.read", "reservation.create", "reservation.update", "reservation.cancel"],
      isSourceOfTruth: false,
      priority: 40,
      updatedAt: relativeIso(-11 * minute),
    },
  ],
  routes: [
    {
      id: "public-route-paris-read",
      restaurantId: "public-pilot-paris",
      capability: "reservation.read",
      primarySystemId: "public-system-paris-native",
      primarySystemName: "Réservations TableNow — démonstration",
      primaryAccessMethod: "native",
      fallbackSystemId: "public-system-paris-calendar",
      fallbackSystemName: "Calendrier de service fictif",
      fallbackAccessMethod: "calendar",
      executionMode: "automatic",
      maximumRisk: "low",
      active: true,
    },
    {
      id: "public-route-paris-create",
      restaurantId: "public-pilot-paris",
      capability: "reservation.create",
      primarySystemId: "public-system-paris-native",
      primarySystemName: "Réservations TableNow — démonstration",
      primaryAccessMethod: "native",
      fallbackSystemId: "public-system-paris-manual",
      fallbackSystemName: "Cahier de secours fictif",
      fallbackAccessMethod: "manual",
      executionMode: "approval",
      maximumRisk: "medium",
      active: true,
    },
    {
      id: "public-route-paris-cancel",
      restaurantId: "public-pilot-paris",
      capability: "reservation.cancel",
      primarySystemId: "public-system-paris-native",
      primarySystemName: "Réservations TableNow — démonstration",
      primaryAccessMethod: "native",
      fallbackSystemId: "public-system-paris-manual",
      fallbackSystemName: "Cahier de secours fictif",
      fallbackAccessMethod: "manual",
      executionMode: "approval",
      maximumRisk: "high",
      active: true,
    },
    {
      id: "public-route-lyon-read",
      restaurantId: "public-pilot-lyon",
      capability: "reservation.read",
      primarySystemId: "public-system-lyon-browser",
      primarySystemName: "Logiciel métier fictif",
      primaryAccessMethod: "browser",
      fallbackSystemId: "public-system-lyon-native",
      fallbackSystemName: "TableNow de secours — démonstration",
      fallbackAccessMethod: "native",
      executionMode: "automatic",
      maximumRisk: "low",
      active: true,
    },
    {
      id: "public-route-lyon-create",
      restaurantId: "public-pilot-lyon",
      capability: "reservation.create",
      primarySystemId: "public-system-lyon-browser",
      primarySystemName: "Logiciel métier fictif",
      primaryAccessMethod: "browser",
      fallbackSystemId: "public-system-lyon-native",
      fallbackSystemName: "TableNow de secours — démonstration",
      fallbackAccessMethod: "native",
      executionMode: "approval",
      maximumRisk: "medium",
      active: true,
    },
  ],
  connections: [
    {
      id: "public-connection-paris",
      restaurantId: "public-pilot-paris",
      provider: "tablenow-simulator",
      displayName: "Interface universelle fictive — Paris",
      surface: "browser",
      baseUrl: "https://paris.public-pilot.invalid",
      allowedHosts: ["paris.public-pilot.invalid"],
      mode: "observe",
      status: "ready",
      capabilities: ["connection.health", "reservation.read", "reservation.create", "reservation.cancel"],
      healthMessage: "Dernier contrôle fictif réussi ; aucune interface réelle n’est connectée.",
      lastVerifiedAt: relativeIso(-8 * minute),
      updatedAt: relativeIso(-8 * minute),
    },
    {
      id: "public-connection-lyon",
      restaurantId: "public-pilot-lyon",
      provider: "generic",
      displayName: "Interface métier fictive — Lyon",
      surface: "browser",
      baseUrl: "https://lyon.public-pilot.invalid",
      allowedHosts: ["lyon.public-pilot.invalid"],
      mode: "observe",
      status: "limited",
      capabilities: ["connection.health", "reservation.read", "reservation.create"],
      healthMessage: "Démonstration limitée à la lecture ; aucune donnée réelle n’est accessible.",
      lastVerifiedAt: relativeIso(-19 * minute),
      updatedAt: relativeIso(-19 * minute),
    },
  ],
  workflows: [
    {
      id: "public-workflow-paris-health",
      connectionId: "public-connection-paris",
      key: "connection.health_check",
      version: 1,
      name: "Vérifier la connexion",
      description: "Simule un contrôle de disponibilité sans modifier aucune donnée.",
      risk: "low",
      approvalRequired: false,
      status: "active",
      successCount: 42,
      failureCount: 1,
      lastSucceededAt: relativeIso(-8 * minute),
      lastFailedAt: relativeIso(-6 * day),
    },
    {
      id: "public-workflow-paris-read",
      connectionId: "public-connection-paris",
      key: "reservation.read",
      version: 3,
      name: "Lire les réservations",
      description: "Présente la lecture contrôlée d’une liste de réservations fictives.",
      risk: "low",
      approvalRequired: false,
      status: "active",
      successCount: 126,
      failureCount: 2,
      lastSucceededAt: relativeIso(-23 * minute),
      lastFailedAt: relativeIso(-9 * day),
    },
    {
      id: "public-workflow-paris-create",
      connectionId: "public-connection-paris",
      key: "reservation.create",
      version: 2,
      name: "Créer une réservation",
      description: "Prépare une réservation fictive et exige une validation humaine avant écriture.",
      risk: "medium",
      approvalRequired: true,
      status: "active",
      successCount: 84,
      failureCount: 3,
      lastSucceededAt: relativeIso(-46 * minute),
      lastFailedAt: relativeIso(-11 * day),
    },
    {
      id: "public-workflow-paris-cancel",
      connectionId: "public-connection-paris",
      key: "reservation.cancel",
      version: 2,
      name: "Annuler une réservation",
      description: "Montre le garde-fou imposant une validation de la direction.",
      risk: "high",
      approvalRequired: true,
      status: "active",
      successCount: 17,
      failureCount: 1,
      lastSucceededAt: relativeIso(-2 * hour),
      lastFailedAt: relativeIso(-13 * day),
    },
    {
      id: "public-workflow-lyon-health",
      connectionId: "public-connection-lyon",
      key: "connection.health_check",
      version: 1,
      name: "Vérifier l’interface métier",
      description: "Simule le contrôle de l’interface fictive de Lyon.",
      risk: "low",
      approvalRequired: false,
      status: "active",
      successCount: 19,
      failureCount: 2,
      lastSucceededAt: relativeIso(-19 * minute),
      lastFailedAt: relativeIso(-4 * day),
    },
    {
      id: "public-workflow-lyon-read",
      connectionId: "public-connection-lyon",
      key: "reservation.read",
      version: 1,
      name: "Lire le service de Lyon",
      description: "Lit une vue fictive sans lancer d’action.",
      risk: "low",
      approvalRequired: false,
      status: "active",
      successCount: 31,
      failureCount: 1,
      lastSucceededAt: relativeIso(-34 * minute),
      lastFailedAt: relativeIso(-7 * day),
    },
  ],
  runs: [
    {
      id: "public-run-awaiting",
      connectionId: "public-connection-paris",
      workflowId: "public-workflow-paris-create",
      objective: "Créer une réservation fictive de quatre couverts à 20 h 30.",
      risk: "medium",
      approvalRequired: true,
      status: "awaiting_approval",
      summary: "Action simulée préparée ; aucune écriture n’a été lancée.",
      errorCode: null,
      attempts: 0,
      maxAttempts: 3,
      cancellationRequested: false,
      startedAt: null,
      completedAt: null,
      createdAt: relativeIso(-7 * minute),
      workflowName: "Créer une réservation",
      connectionName: "Interface universelle fictive — Paris",
      requestedBy: "Visiteur pilote",
    },
    {
      id: "public-run-succeeded",
      connectionId: "public-connection-paris",
      workflowId: "public-workflow-paris-read",
      objective: "Lire la liste fictive et vérifier que le service est accessible.",
      risk: "low",
      approvalRequired: false,
      status: "succeeded",
      summary: "Huit réservations fictives ont été lues, sans modification.",
      errorCode: null,
      attempts: 1,
      maxAttempts: 3,
      cancellationRequested: false,
      startedAt: relativeIso(-37 * minute),
      completedAt: relativeIso(-36 * minute),
      createdAt: relativeIso(-38 * minute),
      workflowName: "Lire les réservations",
      connectionName: "Interface universelle fictive — Paris",
      requestedBy: "Copilot de démonstration",
    },
    {
      id: "public-run-failed",
      connectionId: "public-connection-lyon",
      workflowId: "public-workflow-lyon-read",
      objective: "Vérifier la reprise contrôlée après une indisponibilité fictive.",
      risk: "low",
      approvalRequired: false,
      status: "failed",
      summary: "Le parcours fictif a été arrêté avant toute action.",
      errorCode: "PUBLIC_PILOT_SIMULATED_TIMEOUT",
      attempts: 1,
      maxAttempts: 3,
      cancellationRequested: false,
      startedAt: relativeIso(-72 * minute),
      completedAt: relativeIso(-70 * minute),
      createdAt: relativeIso(-73 * minute),
      workflowName: "Lire le service de Lyon",
      connectionName: "Interface métier fictive — Lyon",
      requestedBy: "Copilot de démonstration",
    },
  ],
  events: [
    {
      id: "public-event-awaiting-1",
      runId: "public-run-awaiting",
      sequence: 1,
      kind: "proposal",
      status: "succeeded",
      message: "Objectif fictif analysé et périmètre limité à une réservation.",
      metadata: { publicPilot: true, writesPerformed: false },
      hasEvidence: false,
      occurredAt: relativeIso(-7 * minute),
    },
    {
      id: "public-event-awaiting-2",
      runId: "public-run-awaiting",
      sequence: 2,
      kind: "approval",
      status: "awaiting_approval",
      message: "Validation humaine requise avant toute exécution.",
      metadata: { publicPilot: true },
      hasEvidence: false,
      occurredAt: relativeIso(-6 * minute),
    },
    {
      id: "public-event-success-1",
      runId: "public-run-succeeded",
      sequence: 1,
      kind: "navigation",
      status: "succeeded",
      message: "Interface fictive ouverte dans un environnement isolé.",
      metadata: { publicPilot: true, host: "paris.public-pilot.invalid" },
      hasEvidence: false,
      occurredAt: relativeIso(-37 * minute),
    },
    {
      id: "public-event-success-2",
      runId: "public-run-succeeded",
      sequence: 2,
      kind: "verification",
      status: "succeeded",
      message: "Liste fictive vérifiée ; aucune donnée n’a été modifiée.",
      metadata: { publicPilot: true, recordsRead: 8 },
      hasEvidence: false,
      occurredAt: relativeIso(-36 * minute),
    },
    {
      id: "public-event-failed-1",
      runId: "public-run-failed",
      sequence: 1,
      kind: "navigation",
      status: "failed",
      message: "Indisponibilité simulée détectée ; arrêt sûr du parcours.",
      metadata: { publicPilot: true, writesPerformed: false },
      hasEvidence: false,
      occurredAt: relativeIso(-70 * minute),
    },
  ],
  nodes: [
    {
      id: "public-node-1",
      name: "Nœud fictif de démonstration",
      status: "online",
      version: "pilot-demo",
      platform: "isolated-simulator",
      capabilities: ["browser.read", "workflow.preview"],
      browserVersion: null,
      healthStatus: "healthy",
      lastHeartbeatAt: relativeIso(-2 * minute),
      lastSeenAt: relativeIso(-2 * minute),
    },
  ],
  generatedAt: relativeIso(0),
};
